version: 2.1
jobs: 
  run_tests:
    docker: 
      - image: circleci/node:16
    environment:
      repo_token: aAlrtM7roCJ3HvDi4UEBwQaKZnfIL3SaU
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: cd SERVER && npm install 
      - run:
          name: Install npm dev dependencies
          command: cd SERVER && npm install mocha nyc chai-http chai
      - run:
          name: Run Unit Tests
          command: cd SERVER && npm test
      - run:
          name: Upload coverage to Coveralls
          command: cd SERVER && npx coveralls < coverage/lcov.info
workflows:
  build_tests:
    jobs:
      - run_tests
