version: '1'
environments:
  production:
    secrets:
      - name: NODE_ENV
        value: "production"
services:
  web:
    image: node
    env:
      PORT: 2000
    command: npm run dev
    ports:
      - 2000:2000